# ordinal_crypto is the cryptography library for the Ordinal Platform

# Copyright (C) 2024 sean watters

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[package]
authors = ["sean watters <sean@watters.io>"]
description = "The cryptography library for the Ordinal Platform 🔐"
edition = "2021"
homepage = "https://github.com/ordinarylabs"
license = "AGPL-3.0"
name = "ordinal_crypto"
readme = "README.md"
repository = "https://github.com/ordinarylabs/ordinal-crypto"
version = "0.3.2"

[dependencies]
base64 = "0.21.2"
blake3 = "0.1.3"

aead = "0.5.2"
aes = "0.8.3"
chacha20poly1305 = { version = "0.10.1", features = ["reduced-round"] }

rand_core = "0.6.4"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
x25519-dalek = { version =  "2.0.0", features = ["static_secrets"] }

[dev-dependencies]
lazy_static = "1.4.0"
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "lib"
harness = false